### ISSUE TITLE
I just upgraded to 1.1.0 and receiving several errors from nodes

### ISSUE THREAD

**Issue by Mavrrick** [Samsung/SamsungAutomationStudio#7]
Working fine with 1.0.16. Upgraded to 1.1.0 and a few things occurred. 

PAT for some reason failed ton continue to work. I had to generate a new token and add to all devices again. 

Then the "installed-device" nodes were generating a error when being redeployed.

"TypeError: Promise.allSettled is not a function"

I have a node to check status and when it is activated with a inject it is generating this error.

"Invalid property or argument value, Cannot read property 'type' of null"

I went back and recreated one of my automations with a endpoint and the Device Profile nodes appear to be creating the same error  as the installed device-profile node.

Then when the endpoint is also generating the same error when then event node is called as the status node above.

These were all working prior to the upgrade to 1.1.0 from 1.0.16.

**Comment by lslomczynski** [comment]
Hello! I nad the same thing with my set-up.

As for the "TypeError: Promise.allSettled is not a function" - I discovered that this function was not available in my Node.js 10.X. I've updated to node 14.X and the problem was gone :-)

As for the "Invalid property or argument value, Cannot read property 'type' of null" - I had this error after reading status of my AC Windfree device. This error was generated by Homekit node from NRCHKB which was also recently updated. I've tracked down that HeaterCooler type device throws this error while passing CurrentHeater-CoolerState and TargetHeeterCoolerState values while AC was OFF. Although I didn't try it with AC ON as at this time of year we have 6 degrees od C outside :-) Maybe it is the same or similar case on your side?

Regards,
Lucas

**Comment by dplaya-min** [comment]
We apologize for any inconvenience this may cause.
It seems that the error occurred because we always used the latest version of Node.
Thank you so much for lslomczynski's comment.
Be careful with the Node version when using Promise.
We will develop the areas that need to be corrected after reviewing the issues added here.
Thank you again.

**Comment by gaggi** [comment]
I also just updated to Version 1.1.0 and get the "Invalid property or argument value, Cannot read property 'type' of null" error on the status nodes for my dryer and fridge.
Had to roll back to 1.0.16 and comment out line 577 to get rid of the nasty warning in the debug window every time i request the status nodes.
